# The Testing workflow creates a kubernetes cluster using kind and
# runs a suite of acceptance tests.

name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0

      - name: Install binaries for testing
      - run: |
          go install ./... 

      - name: View Cluster
      - run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: Run Kubesearch
        run: |
          kubesearch &

      - name: Test
        run: |
          kubectl-search kube